name: attendease
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.3.2
  dio: ^5.11.1
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^11.2.0
  get_it: ^9.3.0
  geolocator: ^14.0.3
  device_info_plus: ^13.2.0
  connectivity_plus: ^7.3.1
  intl: ^0.20.3
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  google_fonts: ^8.2.1
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true

  image_path: "assets/icons/icon.png"

  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/icon.png"

  remove_alpha_ios: true


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/


