// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApP76W6ilFksA3s3co-3bmnJgrsHZTvc4',
    appId: '1:1032977465715:web:64084ff37b668a368b4506',
    messagingSenderId: '1032977465715',
    projectId: 'attendease-37e9d',
    authDomain: 'attendease-37e9d.firebaseapp.com',
    storageBucket: 'attendease-37e9d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq9VPTIMnMI8SBwPNn8ZCTZvHQNhi00Io',
    appId: '1:1032977465715:android:8c799d12d483b82f8b4506',
    messagingSenderId: '1032977465715',
    projectId: 'attendease-37e9d',
    storageBucket: 'attendease-37e9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU8if6imc26GFQ7BNFlQQWPNABWXVgl-0',
    appId: '1:1032977465715:ios:2bd2cd2bf34fb83c8b4506',
    messagingSenderId: '1032977465715',
    projectId: 'attendease-37e9d',
    storageBucket: 'attendease-37e9d.firebasestorage.app',
    iosBundleId: 'com.example.attendease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU8if6imc26GFQ7BNFlQQWPNABWXVgl-0',
    appId: '1:1032977465715:ios:2bd2cd2bf34fb83c8b4506',
    messagingSenderId: '1032977465715',
    projectId: 'attendease-37e9d',
    storageBucket: 'attendease-37e9d.firebasestorage.app',
    iosBundleId: 'com.example.attendease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApP76W6ilFksA3s3co-3bmnJgrsHZTvc4',
    appId: '1:1032977465715:web:44224e888694625a8b4506',
    messagingSenderId: '1032977465715',
    projectId: 'attendease-37e9d',
    authDomain: 'attendease-37e9d.firebaseapp.com',
    storageBucket: 'attendease-37e9d.firebasestorage.app',
  );
}
